apiVersion: apps/v1
kind: Deployment
metadata:
  name: receiver-deployment
spec:
  selector:
    matchLabels:
      app: receiver
  template:
    metadata:
      labels:
        app: receiver
    spec:
      containers:
        - name: receiver
          image: localhost/receiver
          ports:
            - containerPort: 8080
